### ISSUE TITLE
how to compile gdclone from source?

### ISSUE THREAD

**Issue by groggone** [opstic/gdclone#2]

**Comment by opstic** [comment]
It is just a normal Rust project, as long as you have a relatively recent version of the Rust toolchain and Cargo installed (preferably by using rustup), you should be able to just run it with a `cargo run --release` in the project directory.
Here's a link to the docs on how to install the Rust toolchain: https://doc.rust-lang.org/book/ch01-01-installation.html#installation

**Comment by groggone** [comment]
Ok thank you
