### ISSUE TITLE
Web version: load ID from query parameter

### ISSUE THREAD

**Issue by Milk-Cool** [opstic/gdclone#3]
Hello! Cool project, can't wait to see it finished!

While it's being worked on though, I wanted to suggest a feature: loading a level by ID from a query parameter like this:
```
https://opstic.github.io/gdclone?id=10000000
```
or using a hash like this:
```
https://opstic.github.io/gdclone#10000000
```

It would be really cool to see this integrated into websites like GDBrowser so that you can play almost the entirety of GD online :)

**Comment by opstic** [comment]
Oh, this is actually already a feature!
I just didn't know where to put the documentation for it 😅 

Configurable parameters:
- `preload`: Query for level to preload, basically the search bar
- `start_y`: Sets the starting Y position, useful when the level doesn't start at the ground
- `start_scale`: Sets the starting camera scale
- `use_song`: Tells it to download the song or not
- `low_detail`: Toggles the low detail option
- `start_paused`: Starts the level paused

Examples:
https://opstic.github.io/gdclone/?preload=87665224&start_y=1050&low_detail=1: KOCMOC with correct y starting position and low detail
https://opstic.github.io/gdclone/?preload=cosmic+cyclone&use_song=0: Cosmic Cyclone with song disabled
https://opstic.github.io/gdclone/?preload=60978746&start_paused=1: The Golden that's paused on load

Edit:
Wiki link here: https://github.com/opstic/gdclone/wiki/Configurable-Web-Parameters

**Comment by NexusSfan** [comment]
> Oh, this is actually already a feature! I just didn't know where to put the documentation for it 😅

Maybe you could create a Github Wiki page where you put the documentation once ready.

**Comment by opstic** [comment]
> Maybe you could create a Github Wiki page where you put the documentation

Done!
